package com.longdq.adaptengbackend.enums;

public enum KnowledgeType {
    // === NHÓM 1: TỪ VỰNG ===
    VOCABULARY, WORD_FORMATION, COLLOCATIONS, PHRASAL_VERBS, SYNONYM,

    // === NHÓM 2: ĐẠI TỪ & TỪ HẠN ĐỊNH ===
    PRONOUNS_PERSONAL, PRONOUNS_POSSESSIVE, PRONOUNS_REFLEXIVE, PRONOUNS_INDEFINITE,
    NOUNS_COUNTABLE_UNCOUNTABLE, QUANTIFIERS, ARTICLES,

    // === NHÓM 3: GIỚI TỪ & LIÊN TỪ ===
    PREPOSITIONS_TIME, PREPOSITIONS_PLACE, PREPOSITIONS_OTHER,
    COORDINATING_CONJUNCTIONS, SUBORDINATING_CONJUNCTIONS, CORRELATIVE_CONJUNCTIONS,

    // === NHÓM 4: ĐỘNG TỪ & THỂ BỊ ĐỘNG & SỰ HÒA HỢP ===
    SUBJECT_VERB_AGREEMENT, PASSIVE_VOICE, MODAL_VERBS,
    GERUNDS, INFINITIVES, PARTICIPLES,

    // === NHÓM 5: CÂU ĐIỀU KIỆN (Đã chia nhỏ) ===
    CONDITIONAL_TYPE_1, CONDITIONAL_TYPE_2, CONDITIONAL_TYPE_3, CONDITIONAL_MIXED,

    // === NHÓM 6: CẤU TRÚC SO SÁNH (Đã chia nhỏ) ===
    COMPARISON_EQUALITY, COMPARISON_COMPARATIVE, COMPARISON_SUPERLATIVE,

    // === NHÓM 7: MỆNH ĐỀ ===
    RELATIVE_CLAUSES, NOUN_CLAUSES, ADVERBIAL_CLAUSES,

    // === NHÓM 8: TÍNH TỪ & TRẠNG TỪ ===
    ADJECTIVES, ADVERBS,

    // === NHÓM 9: 12 THÌ TIẾNG ANH (TENSES) ===
    PRESENT_SIMPLE, PRESENT_CONTINUOUS, PRESENT_PERFECT, PRESENT_PERFECT_CONTINUOUS,
    PAST_SIMPLE, PAST_CONTINUOUS, PAST_PERFECT, PAST_PERFECT_CONTINUOUS,
    FUTURE_SIMPLE, FUTURE_CONTINUOUS, FUTURE_PERFECT, FUTURE_PERFECT_CONTINUOUS,

    // === NHÓM 10: KỸ NĂNG NGỮ CẢNH & ĐỌC HIỂU (Tracking & On-Demand) ===
    TRANSITIONS,
    TEXT_COHESION,
    MAIN_IDEA,
    AUTHOR_PURPOSE,
    SPECIFIC_DETAILS,
    INFERENCE,
    CROSS_REFERENCING,
    NOT_TRUE_QUESTION,
    SENTENCE_INSERTION
}