spring:
  application:
    name: adapt-eng-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/adapt_eng_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
gemini:
    api:
      key: ""
      url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
